package gps;

import gps.pathfinder.CollisionMap;
import gps.pathfinder.PathfinderConfig;
import gps.pathfinder.TestPathfinderConfig;
import gps.transport.Transport;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import net.runelite.api.Client;
import net.runelite.api.GameState;
import org.junit.Assume;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Mock;
import org.mockito.junit.MockitoJUnitRunner;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Repairs the unreachable-destination backlog (enable with -DsnapFix=true). Two outputs:
 *
 * 1. SNAP — pins whose tile isn't reachable but which have a reachable tile within
 *    {@link #MAX_SNAP} are rewritten onto it. These are pins on the wrong TILE: the amenity dump
 *    pinned the object (an altar's tiles, a bank booth) instead of the tile you stand on to use
 *    it. Rows that collapse onto the same place are de-duplicated. Only already-broken pins are
 *    touched, and only by a few tiles.
 * 2. TODO — everything still sealed is grouped by building/area into a field checklist, with the
 *    nearest reachable tile to walk to, so the missing entrances can be mapped with the audit.
 */
@RunWith(MockitoJUnitRunner.Silent.class)
public class DestinationSnapFixTest
{
	private static final int LUMBRIDGE = WorldPointUtil.packWorldPoint(3222, 3218, 0);
	private static final int INSTANCE_MIN_Y = 4160;
	private static final int INSTANCE_MAX_Y = 8000;
	private static final int MAX_SNAP = 12;
	private static final int TODO_SEARCH = 60;
	private static final String[] FILES = {"destinations.tsv", "destinations-wiki.tsv"};

	@Mock
	Client client;
	@Mock
	ShortestPathConfig config;

	private Set<Integer> reachable;
	private CollisionMap map;

	@Test
	public void snapAndReport() throws IOException
	{
		Assume.assumeTrue(Boolean.getBoolean("snapFix"));
		flood();

		List<String[]> sealed = new ArrayList<>();
		int snapped = 0;
		int dropped = 0;
		for (String file : FILES)
		{
			Path path = Paths.get("src/main/resources/" + file);
			List<String> lines = Files.readAllLines(path, StandardCharsets.UTF_8);
			List<String> out = new ArrayList<>(lines.size());
			Set<String> seen = new LinkedHashSet<>();
			for (String line : lines)
			{
				String[] fields = line.split("\t", -1);
				if (line.startsWith("#") || line.isBlank() || fields.length < 5
					|| !fields[2].trim().matches("\\d+"))
				{
					out.add(line);
					continue;
				}
				int x = Integer.parseInt(fields[2].trim());
				int y = Integer.parseInt(fields[3].trim());
				int plane = Integer.parseInt(fields[4].trim());
				int packed = WorldPointUtil.packWorldPoint(x, y, plane);
				if (!(y >= INSTANCE_MIN_Y && y <= INSTANCE_MAX_Y) && !anyReachable(packed))
				{
					int snap = nearestReachable(x, y, plane, MAX_SNAP);
					if (snap != WorldPointUtil.UNDEFINED)
					{
						fields[2] = String.valueOf(WorldPointUtil.unpackWorldX(snap));
						fields[3] = String.valueOf(WorldPointUtil.unpackWorldY(snap));
						snapped++;
						line = String.join("\t", fields);
					}
					else
					{
						sealed.add(new String[]{fields[0], fields[1], String.valueOf(x),
							String.valueOf(y), String.valueOf(plane)});
					}
				}
				// Collapse rows that now name the same place at the same tile.
				String key = fields[0] + "|" + fields[1] + "|" + fields[2] + "|" + fields[3]
					+ "|" + fields[4];
				if (!seen.add(key))
				{
					dropped++;
					continue;
				}
				out.add(line);
			}
			Files.write(path, String.join("\n", out).concat("\n").getBytes(StandardCharsets.UTF_8));
		}
		System.out.println("snapped " + snapped + " pins onto reachable tiles, dropped "
			+ dropped + " duplicates, " + sealed.size() + " still sealed");
		writeTodo(sealed);
	}

	/** Groups sealed pins by area and writes a field checklist with somewhere to walk to. */
	private void writeTodo(List<String[]> sealed) throws IOException
	{
		Map<String, List<String[]>> byArea = new TreeMap<>();
		for (String[] pin : sealed)
		{
			int x = Integer.parseInt(pin[2]);
			int y = Integer.parseInt(pin[3]);
			byArea.computeIfAbsent((x / 32 * 32) + "," + (y / 32 * 32) + "," + pin[4],
				k -> new ArrayList<>()).add(pin);
		}
		List<Map.Entry<String, List<String[]>>> areas = new ArrayList<>(byArea.entrySet());
		areas.sort((a, b) -> b.getValue().size() - a.getValue().size());

		StringBuilder md = new StringBuilder();
		md.append("# Unreachable destination areas — field checklist\n\n");
		md.append("Generated by `DestinationSnapFixTest -DsnapFix=true`. Each block is a place ")
			.append("with amenities GPS can't route to, meaning its entrance (staircase, door, ")
			.append("cave) has no transport row. Walk to the suggested tile, then map the way in ")
			.append("with the audit plugin — one staircase usually unseals the whole list.\n\n");
		md.append("Total sealed pins: ").append(sealed.size())
			.append(" in ").append(areas.size()).append(" areas.\n\n");
		for (Map.Entry<String, List<String[]>> area : areas)
		{
			List<String[]> pins = area.getValue();
			int cx = Integer.parseInt(area.getKey().split(",")[0]) + 16;
			int cy = Integer.parseInt(area.getKey().split(",")[1]) + 16;
			int plane = Integer.parseInt(area.getKey().split(",")[2]);
			int walkTo = nearestReachable(cx, cy, plane, TODO_SEARCH);
			if (walkTo == WorldPointUtil.UNDEFINED && plane > 0)
			{
				walkTo = nearestReachable(cx, cy, 0, TODO_SEARCH);
			}
			md.append("## ").append(pins.size()).append(" pins near ").append(cx).append(",")
				.append(cy).append(" (plane ").append(plane).append(")\n");
			md.append("- [ ] walk to **")
				.append(walkTo == WorldPointUtil.UNDEFINED ? "(nothing reachable within "
					+ TODO_SEARCH + " tiles)"
					: WorldPointUtil.unpackWorldX(walkTo) + ", " + WorldPointUtil.unpackWorldY(walkTo)
						+ ", " + WorldPointUtil.unpackWorldPlane(walkTo))
				.append("** and map the entrance\n");
			Set<String> names = new LinkedHashSet<>();
			for (String[] pin : pins)
			{
				names.add(pin[0] + " " + pin[1]);
			}
			md.append("- sealed: ");
			int shown = 0;
			for (String name : names)
			{
				if (shown++ > 0)
				{
					md.append(", ");
				}
				if (shown > 8)
				{
					md.append("… +").append(names.size() - 8).append(" more");
					break;
				}
				md.append(name);
			}
			md.append("\n\n");
		}
		Path out = Paths.get("build/unreachable-areas.md");
		Files.write(out, md.toString().getBytes(StandardCharsets.UTF_8));
		System.out.println("checklist written to " + out.toAbsolutePath());
	}

	private int nearestReachable(int x, int y, int plane, int maxRadius)
	{
		for (int radius = 1; radius <= maxRadius; radius++)
		{
			for (int dx = -radius; dx <= radius; dx++)
			{
				for (int dy = -radius; dy <= radius; dy++)
				{
					if (Math.max(Math.abs(dx), Math.abs(dy)) != radius)
					{
						continue;
					}
					int candidate = WorldPointUtil.packWorldPoint(x + dx, y + dy, plane);
					if (reachable.contains(candidate))
					{
						return candidate;
					}
				}
			}
		}
		return WorldPointUtil.UNDEFINED;
	}

	private boolean anyReachable(int packed)
	{
		for (int target : Destinations.walkableTargets(map, packed))
		{
			if (reachable.contains(target))
			{
				return true;
			}
		}
		return false;
	}

	private void flood()
	{
		when(config.calculationCutoff()).thenReturn(120);
		when(config.useTeleportationItems()).thenReturn(gps.TeleportationItem.ALL);
		when(client.getGameState()).thenReturn(GameState.LOGGED_IN);
		when(client.getClientThread()).thenReturn(Thread.currentThread());
		TestPathfinderConfig testConfig = new TestPathfinderConfig(client, config);
		// Universal bank: reachable means "a player CAN get there" — any obtainable item is
		// assumed owned (dashboard's BANK-preset pattern), else item-gated teleports like the
		// Sailors' amulet would wrongly strand their destinations (Port Roberts).
		net.runelite.api.ItemContainer universalBank = mock(net.runelite.api.ItemContainer.class);
		net.runelite.api.Item[] everyItem = new net.runelite.api.Item[40000];
		for (int i = 0; i < everyItem.length; i++)
		{
			everyItem[i] = new net.runelite.api.Item(i, 1000);
		}
		when(universalBank.getItems()).thenReturn(everyItem);
		testConfig.bank = universalBank;
		PathfinderConfig planning = testConfig.copyForPlanning();
		planning.refresh();
		map = planning.getMap();
		PrimitiveIntHashMap<Transport[]> transports = planning.getTransportsPacked(true);
		reachable = new HashSet<>(1 << 20);
		ArrayDeque<Integer> queue = new ArrayDeque<>();
		reachable.add(LUMBRIDGE);
		queue.add(LUMBRIDGE);
		// ORIGIN-LESS teleports (jewellery, tablets, spells) work ANYWHERE, so their landing
		// tiles are reachable outright. Keyed under UNDEFINED_ORIGIN rather than a tile, they
		// were invisible to a walk-the-graph flood — which made every teleport-only place,
		// Port Roberts included, look sealed.
		Transport[] anywhere = transports.get(Transport.UNDEFINED_ORIGIN);
		if (anywhere != null)
		{
			for (Transport transport : anywhere)
			{
				if (transport.getDestination() != WorldPointUtil.UNDEFINED
					&& reachable.add(transport.getDestination()))
				{
					queue.add(transport.getDestination());
				}
			}
		}
		while (!queue.isEmpty())
		{
			int at = queue.poll();
			int x = WorldPointUtil.unpackWorldX(at);
			int y = WorldPointUtil.unpackWorldY(at);
			int plane = WorldPointUtil.unpackWorldPlane(at);
			for (int dx = -1; dx <= 1; dx++)
			{
				for (int dy = -1; dy <= 1; dy++)
				{
					int next = WorldPointUtil.packWorldPoint(x + dx, y + dy, plane);
					if ((dx != 0 || dy != 0) && !reachable.contains(next) && map.canStep(at, next))
					{
						reachable.add(next);
						queue.add(next);
					}
				}
			}
			Transport[] from = transports.get(at);
			if (from != null)
			{
				for (Transport transport : from)
				{
					int destination = transport.getDestination();
					if (destination != WorldPointUtil.UNDEFINED && reachable.add(destination))
					{
						queue.add(destination);
					}
				}
			}
		}
	}
}
