package gps;

import gps.pathfinder.CollisionMap;
import gps.pathfinder.PathStep;
import gps.pathfinder.Pathfinder;
import gps.pathfinder.PathfinderConfig;
import gps.pathfinder.SplitFlagMap;
import gps.pathfinder.TestPathfinderConfig;
import gps.transport.Transport;
import java.lang.reflect.Proxy;
import java.util.List;
import java.util.Map;
import java.util.Set;
import net.runelite.api.Client;
import net.runelite.api.GameState;
import net.runelite.api.Item;
import net.runelite.api.ItemComposition;
import net.runelite.api.ItemContainer;
import net.runelite.api.QuestState;
import net.runelite.api.gameval.InventoryID;
import net.runelite.api.gameval.ItemID;
import org.junit.Test;
import org.mockito.Mockito;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

/**
 * Capture gps-capture-20261004-184332: the route's first step was "Amulet of glory: Draynor
 * Village" and the glory in the bag was not marked. Routes are generated by planning copies under
 * the route mode, but the overlays resolve a step's transports against the plugin's MAIN config,
 * whose hidden legacy item setting defaults to permanent items only: a charged glory is not
 * "usable" there, the edge resolved to nothing, and the cue had no item to name. A method edge of
 * the displayed route now resolves to the route's own method whatever the main config allows.
 */
public class GloryCueTest
{
	private static final int START = WorldPointUtil.packWorldPoint(2893, 3465, 0);
	private static final int TARGET = WorldPointUtil.packWorldPoint(3093, 3245, 0);

	@Test
	public void aConsumableTeleportStepResolvesAgainstTheLegacyMainConfig()
	{
		Client client = clientWithGlory();
		PathfinderConfig owned = new TestPathfinderConfig(client, config(TeleportationItem.INVENTORY), QuestState.FINISHED, true, true);
		owned.refresh();
		CollisionMap map = new CollisionMap(SplitFlagMap.fromResources());
		Pathfinder pathfinder = new Pathfinder(owned, START, Destinations.walkableTargets(map, TARGET));
		pathfinder.run();
		List<PathStep> path = pathfinder.getPath();
		Set<Transport> generated = EdgeTransports.forEdge(owned, path.get(0), path.get(1));
		assertEquals("the route's first step is one teleport", 1, generated.size());
		Transport glory = generated.iterator().next();
		assertEquals("Amulet of glory: Draynor Village", glory.getDisplayInfo());
		RouteOption route = new RouteOption(path, List.of(glory.method()), List.of(1), List.of(4), 22, 22, true, Set.of(),
			List.of(0), path.size() - 2);

		// The plugin's main config: permanent items only, as the hidden setting defaults.
		PathfinderConfig main = new TestPathfinderConfig(client, config(TeleportationItem.INVENTORY_NON_CONSUMABLE),
			QuestState.FINISHED, true, true);
		main.refresh();
		assertTrue("the main config does not count a charged glory", EdgeTransports.forEdge(main, path.get(0), path.get(1)).isEmpty());

		Set<Transport> resolved = EdgeTransports.forRouteEdge(main, route, path.get(0), path.get(1));
		assertTrue("the route's own method resolves anyway", resolved.stream().anyMatch(t -> glory.method().equals(t.method())));
		RouteItemCue cue = RouteItemCue.next(route, 0, (a, b) -> EdgeTransports.forRouteEdge(main, route, a, b), true,
			Map.of(ItemID.AMULET_OF_GLORY_4, 1));
		assertNotNull("the glory step has a cue", cue);
		assertTrue("the held glory is in it: " + cue.itemIds, cue.itemIds.contains(ItemID.AMULET_OF_GLORY_4));

		// The step list calls the item out under its step, the way the withdraw step lists its items;
		// the verb sits on the item line only, so the step's own line drops its "Use".
		ShortestPathPlugin plugin = Mockito.mock(ShortestPathPlugin.class);
		Mockito.when(plugin.getClient()).thenReturn(client);
		Mockito.when(plugin.getPathfinderConfig()).thenReturn(main);
		List<RouteDirections.Step> steps = RouteDirections.build(plugin, route);
		assertEquals("Amulet of glory: Draynor Village", steps.get(0).getText());
		assertEquals(List.of("Use Amulet of glory(4)"), steps.get(0).getDetails());

		// With nothing to call out (the glory is not carried) the step keeps its own verb.
		Client emptyHanded = emptyHanded();
		Mockito.when(plugin.getClient()).thenReturn(emptyHanded);
		assertEquals("Use Amulet of glory: Draynor Village", RouteDirections.build(plugin, route).get(0).getText());

		// A walking edge of the same route is untouched: whatever the main config finds, nothing here.
		assertEquals(EdgeTransports.forEdge(main, path.get(1), path.get(2)), EdgeTransports.forRouteEdge(main, route, path.get(1), path.get(2)));
		assertEquals("no route, no change", Set.of(), EdgeTransports.forRouteEdge(main, null, path.get(0), path.get(1)));
	}

	private static ShortestPathConfig config(TeleportationItem items)
	{
		return Mockito.mock(ShortestPathConfig.class, invocation ->
		{
			String name = invocation.getMethod().getName();
			Class<?> type = invocation.getMethod().getReturnType();
			if (type == boolean.class)
			{
				return !"avoidWilderness".equals(name);
			}
			if (type == int.class)
			{
				return "calculationCutoff".equals(name) ? 120 : 0;
			}
			if (type == TeleportationItem.class)
			{
				return items;
			}
			return HybridPageFillTest.defaultValue(type);
		});
	}

	/** A logged-in client carrying one Amulet of glory(4). */
	private static Client clientWithGlory()
	{
		return client(new Item[]{new Item(ItemID.AMULET_OF_GLORY_4, 1)});
	}

	private static Client emptyHanded()
	{
		return client(new Item[0]);
	}

	private static Client client(Item[] items)
	{
		final Thread clientThread = Thread.currentThread();
		ItemContainer inventory = Mockito.mock(ItemContainer.class);
		Mockito.when(inventory.getItems()).thenReturn(items);
		return (Client) Proxy.newProxyInstance(Client.class.getClassLoader(), new Class<?>[]{Client.class},
			(proxy, method, args) ->
			{
				switch (method.getName())
				{
					case "getGameState":
						return GameState.LOGGED_IN;
					case "getClientThread":
						return clientThread;
					case "getBoostedSkillLevel":
						return 99;
					case "getItemContainer":
						return (int) args[0] == InventoryID.INV ? inventory : null;
					case "getItemDefinition":
						ItemComposition item = Mockito.mock(ItemComposition.class);
						Mockito.when(item.getName()).thenReturn((int) args[0] == ItemID.AMULET_OF_GLORY_4 ? "Amulet of glory(4)" : "Item");
						return item;
					default:
						return HybridPageFillTest.defaultValue(method.getReturnType());
				}
			});
	}
}
