#!/usr/bin/env python3
"""
TSV Consistency Checker

Validates the plugin's TSV resources. Four file families share one checker:
  transport rows (transports/, destinations/*/, leagues/): a '#'-prefixed header;
  plain-header tables (destinations*.tsv, doors.tsv, sailing-*.tsv): free '#' comment
  lines, then a plain header line; and two headerless box lists (destination-exclusions,
  destination-remaps) with a fixed column count and a trailing free-text column.
  1. The header (where the family has one) names only columns the loaders know
  2. Column names must all be recognized by the parser
  3. Column count: a data row may omit trailing empty cells (every loader splits without
     a limit, so trailing empties vanish) but never carries MORE cells than the header;
     '#' comment rows are skipped exactly as the loaders skip them
  4. Origin/Destination cells must be 'x y plane' coordinates (or empty)
  5. Skill-like values ('N SkillName') must not appear in Items columns
  6. Items column values must follow 'NAME=qty' format (& / | separated)
  7. Skills column values must follow 'N SkillName' format (; separated)
  8. Varbits/VarPlayers must follow 'id<op>value' format (; separated)
  9. Duration must be a positive integer
 10. Wilderness level must be a non-negative integer
 11. Consumable must be 'T' or 'F'

Usage:
  python3 check_tsv.py [directory]

  directory  Path to search for *.tsv files (default: ../src/main/resources)
"""

import os
import re
import sys
import glob

# ---------------------------------------------------------------------------
# Constants matching TransportRecord.Fields and destination TSV headers
# ---------------------------------------------------------------------------
KNOWN_COLUMNS = {
    "Origin",
    "Destination",
    "menuOption menuTarget objectID",
    "Skills",
    "Items",
    "Quests",
    "Duration",
    "Display info",
    "Consumable",
    "Wilderness level",
    "Varbits",
    "VarPlayers",
    "Region override",
    # Free-text advisory shown in the step list, and provenance/tooling metadata
    "Note",
    "Meta",
    # Destination-file-only columns
    "Info",
    # leagues/regions.tsv columns (regionId -> LeagueRegion mapping
    # auto-generated by shortest-path-tooling's leagueRegionDump task)
    "regionId",
    "LeagueRegion",
    # destinations*.tsv (category name x y plane [verified_source verified_date])
    "category", "name", "x", "y", "plane", "verified_source", "verified_date",
    # doors.tsv (id name x y plane type orientation sizeX sizeY state)
    "id", "type", "orientation", "sizeX", "sizeY", "state",
    # sailing-moorings.tsv (type landX landY waterX waterY reachable name),
    # sailing-ports.tsv (portId name landX landY),
    # sailing-sea-matrix.tsv (fromLandX fromLandY toLandX toLandY centitiles)
    "landX", "landY", "waterX", "waterY", "reachable", "portId",
    "fromLandX", "fromLandY", "toLandX", "toLandY", "centitiles",
}

# Files with no header at all: a fixed number of columns, the last one free text.
HEADERLESS = {
    # x1 y1 x2 y2 plane comment
    "destination-exclusions.tsv": 6,
    # x1 y1 x2 y2 plane anchorX anchorY anchorPlane comment
    "destination-remaps.tsv": 9,
}

SKILL_NAMES = {
    "attack", "strength", "defence", "ranged", "prayer", "magic",
    "runecraft", "hitpoints", "crafting", "mining", "smithing",
    "fishing", "cooking", "firemaking", "woodcutting", "agility",
    "herblore", "thieving", "fletching", "slayer", "farming",
    "construction", "hunter", "summoning", "dungeoneering",
    "divination", "invention", "archaeology", "necromancy",
    "sailing", "total", "combat", "quest", "points",
}

# Varbit/VarPlayer operator characters (from VarCheckType enum)
_VAR_REQ = re.compile(r"^\d+[=><&@]\d+$")
# World coordinate: 'x y plane'
_COORD = re.compile(r"^\d+ \d+ \d+$")
# Item requirement part after normalization: 'NAME=qty' where NAME is [A-Z0-9_]
_ITEM_PART = re.compile(r"^[A-Z0-9_]+=\d+$")

# Valid LeagueRegion enum values for the 'Region override' column.
# Must match shortestpath.leagues.LeagueRegion exactly (case-sensitive).
LEAGUE_REGIONS = {
    "VARLAMORE",
    "KARAMJA",
    "ASGARNIA",
    "KANDARIN",
    "FREMENNIK",
    "KOUREND",
    "WILDERNESS",
    "MORYTANIA",
    "DESERT",
    "TIRANNWN",
    "MISTHALIN",
    "NEUTRAL",
}

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DEFAULT_DIR = os.path.join(SCRIPT_DIR, "..", "src", "main", "resources")


# ---------------------------------------------------------------------------
# Field validators
# ---------------------------------------------------------------------------

def looks_like_skill(value):
    """Return True if value looks like a skill requirement, e.g. '35 Construction'."""
    parts = value.strip().split()
    if len(parts) == 2:
        try:
            int(parts[0])
            name = parts[1].lower()
            if name in SKILL_NAMES or name.rstrip("s") in SKILL_NAMES:
                return True
        except ValueError:
            pass
    return False


def validate_coordinate(value):
    """Return error string if value is not a valid coordinate (or empty for permutations)."""
    v = value.strip()
    if not v:
        return None  # empty = location permutation, valid
    if not _COORD.match(v):
        return f"invalid coordinate '{v}' (expected 'x y plane')"
    return None


def validate_skills(value):
    """Return error strings for any bad skill requirement (';' separated)."""
    errors = []
    for part in value.split(";"):
        part = part.strip()
        if not part:
            continue
        if not looks_like_skill(part):
            errors.append(f"invalid skill requirement '{part}' (expected 'N SkillName')")
    return errors


def validate_items(value):
    """Return error strings for any bad item requirement ('&' and '|' separated)."""
    errors = []
    # Normalize: strip spaces, collapse double operators, uppercase — mirrors ItemRequirementParser
    normalized = value.replace(" ", "").replace("&&", "&").replace("||", "|").upper()
    for and_part in normalized.split("&"):
        for or_part in and_part.split("|"):
            if not or_part:
                continue
            if not _ITEM_PART.match(or_part):
                errors.append(
                    f"invalid item requirement '{or_part}' in '{value}' "
                    f"(expected 'NAME=qty')"
                )
    return errors


def validate_var_requirements(value):
    """Return error strings for bad varbit/varplayer requirements (';' separated)."""
    errors = []
    for part in value.split(";"):
        part = part.strip()
        if not part:
            continue
        if not _VAR_REQ.match(part):
            errors.append(
                f"invalid var requirement '{part}' "
                f"(expected '<id><op><value>' where op is one of = > < & @)"
            )
    return errors


def validate_duration(value):
    """Return error string if value is not a positive integer."""
    v = value.strip()
    if not v:
        return None
    try:
        if int(v) <= 0:
            return f"duration '{v}' must be a positive integer"
    except ValueError:
        return f"duration '{v}' is not an integer"
    return None


def validate_wilderness_level(value):
    """Return error string if value is not a non-negative integer."""
    v = value.strip()
    if not v:
        return None
    try:
        if int(v) < 0:
            return f"wilderness level '{v}' must be >= 0"
    except ValueError:
        return f"wilderness level '{v}' is not an integer"
    return None


def validate_consumable(value):
    """Return error string if value is not a recognised consumable flag."""
    v = value.strip()
    if not v:
        return None
    if v not in ("T", "F"):
        return f"consumable '{v}' must be 'T' or 'F'"
    return None


def validate_region_override(value):
    """Return error string if value is not a valid LeagueRegion name."""
    v = value.strip()
    if not v:
        return None
    if v not in LEAGUE_REGIONS:
        return (
            f"region override '{v}' is not a valid LeagueRegion "
            f"(expected one of: {', '.join(sorted(LEAGUE_REGIONS))})"
        )
    return None


def validate_integer(value):
    """Return error string if value is not an integer."""
    v = value.strip()
    if not v:
        return None
    if not re.fullmatch(r"-?\d+", v):
        return f"'{v}' is not an integer"
    return None


def validate_plane(value):
    """Return error string if value is not a plane 0..3."""
    v = value.strip()
    if not v:
        return None
    if not re.fullmatch(r"[0-3]", v):
        return f"'{v}' is not a plane (0-3)"
    return None


# Map column name → validator function
COLUMN_VALIDATORS = {
    "x":                validate_integer,
    "y":                validate_integer,
    "plane":            validate_plane,
    "id":               validate_integer,
    "landX":            validate_integer,
    "landY":            validate_integer,
    "waterX":           validate_integer,
    "waterY":           validate_integer,
    "fromLandX":        validate_integer,
    "fromLandY":        validate_integer,
    "toLandX":          validate_integer,
    "toLandY":          validate_integer,
    "centitiles":       validate_integer,
    "portId":           validate_integer,
    "Origin":           validate_coordinate,
    "Destination":      validate_coordinate,
    "Skills":           validate_skills,
    "Items":            validate_items,
    "Varbits":          validate_var_requirements,
    "VarPlayers":       validate_var_requirements,
    "Duration":         validate_duration,
    "Wilderness level": validate_wilderness_level,
    "Consumable":       validate_consumable,
    "Region override":  validate_region_override,
}


# ---------------------------------------------------------------------------
# Per-file checker
# ---------------------------------------------------------------------------

def find_header(lines):
    """
    The header line index and its column names, or (None, None) for a headerless file.
    Transport files put the header on line 1 behind '#'; the plain-header tables and the
    generated sailing files carry free '#' comment lines (no tabs) first, then either a
    '#'-prefixed or a plain tab-separated header.
    """
    for index, raw in enumerate(lines):
        line = raw.rstrip("\n")
        if not line.strip():
            continue
        if line.startswith("#"):
            body = line.lstrip("#").strip()
            if "\t" in body:
                return index, [h.strip() for h in body.split("\t")]
            if body in KNOWN_COLUMNS:
                # A one-column header ("# Destination" on a bare tile list).
                return index, [body]
            # A free comment line (no tabs): keep looking for the header.
            continue
        if "\t" in line and not re.match(r"^\d", line):
            return index, [h.strip() for h in line.split("\t")]
        return None, None
    return None, None


def check_tsv(filepath):
    """Check a single TSV file. Returns a list of issue strings (empty = clean)."""
    issues = []
    with open(filepath, "r", encoding="utf-8") as f:
        lines = f.readlines()

    if not lines:
        return issues

    basename = os.path.basename(filepath)
    if basename in HEADERLESS:
        return check_headerless(lines, HEADERLESS[basename])

    header_index, headers = find_header(lines)
    if headers is None:
        issues.append("  no header line found (a '#'-prefixed or plain tab-separated column list)")
        return issues
    num_cols = len(headers)

    # Check 1-2: every column name is one the loaders know.
    for col in headers:
        if col not in KNOWN_COLUMNS:
            issues.append(f"  unknown column name: '{col}'")

    validators = [COLUMN_VALIDATORS.get(h) for h in headers]

    col_count_errors = 0
    for lineno, raw in enumerate(lines[header_index + 1:], start=header_index + 2):
        line = raw.rstrip("\n")
        if not line.strip() or line.startswith("#"):
            # Blank and comment rows are skipped by every loader.
            continue

        cols = line.split("\t")

        # Check 3: never MORE cells than the header; trailing empties may be omitted.
        if len(cols) > num_cols:
            col_count_errors += 1
            if col_count_errors <= 5:
                issues.append(
                    f"  line {lineno}: expected at most {num_cols} columns, found {len(cols)} "
                    f"({len(cols) - num_cols} extra tab(s))"
                )
            continue

        # Check 4-11: per-cell validators
        for col_idx, (col_val, validator) in enumerate(zip(cols, validators)):
            if validator is None or not col_val.strip():
                continue
            result = validator(col_val)
            if result is None:
                continue
            errors = result if isinstance(result, list) else [result]
            col_name = headers[col_idx]
            for err in errors:
                issues.append(f"  line {lineno} [{col_name}]: {err}")

    if col_count_errors > 5:
        issues.append(f"  ... and {col_count_errors - 5} more column-count errors")

    return issues


def check_headerless(lines, num_cols):
    """A box list: every data row has exactly num_cols cells, the leading ones integers."""
    issues = []
    for lineno, raw in enumerate(lines, start=1):
        line = raw.rstrip("\n")
        if not line.strip() or line.startswith("#"):
            continue
        cols = line.split("\t")
        if len(cols) != num_cols:
            issues.append(f"  line {lineno}: expected {num_cols} columns, found {len(cols)}")
            continue
        for col_idx, col_val in enumerate(cols[:-1]):
            err = validate_integer(col_val)
            if err:
                issues.append(f"  line {lineno} [column {col_idx + 1}]: {err}")
    return issues


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    resource_dir = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_DIR

    tsv_files = sorted(
        glob.glob(os.path.join(resource_dir, "**", "*.tsv"), recursive=True)
    )

    if not tsv_files:
        print(f"No TSV files found under: {resource_dir}", file=sys.stderr)
        sys.exit(1)

    any_issues = False
    for filepath in tsv_files:
        rel = os.path.relpath(filepath)
        issues = check_tsv(filepath)
        if issues:
            any_issues = True
            print(f"FAIL  {rel}")
            for issue in issues:
                print(issue)
        else:
            print(f"ok    {rel}")

    print()
    if any_issues:
        print("TSV consistency check FAILED.")
        sys.exit(1)
    else:
        print("TSV consistency check passed.")


if __name__ == "__main__":
    main()

