#!/usr/bin/env python3
"""Generate the Spellbook Swap variants of the teleport spells (issue #14).

Spellbook Swap (Lunar, 96 Magic, Dream Mentor, 3 astral + 2 cosmic + 1 law, 4 ticks) lets a
player on the Lunar spellbook cast ONE spell from another book. For every standard, ancient and
Arceuus teleport spell row (home teleports excluded: they cannot be swapped to) this writes a
variant with the same destination and display name, so it is the same catalog method:

  Items     the spell's runes plus the swap's, quantities merged per rune
  Skills    96 Magic (or the spell's own level when higher)
  Quests    the spell's quests plus Dream Mentor
  Duration  the spell's plus 5 (the swap's four ticks and the pick)
  Varbits   4070=2 (on Lunars) in place of the spell's own book, other conditions kept
  Note      "Spellbook Swap first": what the step list prints and the spellbook frame reads

The block between the markers is regenerated on every run; the base rows are the source of
truth, so edit those and rerun:

  python scripts/derive_spellbook_swap.py
"""
import io
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
PATH = os.path.join(ROOT, 'src', 'main', 'resources', 'transports', 'teleportation_spells.tsv')
BEGIN = '# >>> Spellbook Swap variants: generated by scripts/derive_spellbook_swap.py from the rows above, do not edit'
END = '# <<< Spellbook Swap variants'
SWAP_RUNES = {'ASTRAL_RUNE': 3, 'COSMIC_RUNE': 2, 'LAW_RUNE': 1}
SWAP_TICKS = 5
SWAP_LEVEL = 96
SWAP_QUEST = 'Dream Mentor'
NOTE = 'Spellbook Swap first: 3 astral, 2 cosmic, 1 law'


def merged_items(items):
    """The spell's rune requirements plus the swap's, summed per rune family."""
    parts = [p for p in re.split(r'&&|&', items) if p] if items else []
    out = []
    seen = {}
    for part in parts:
        if '|' in part or '=' not in part:
            out.append(part)
            continue
        name, qty = part.split('=', 1)
        seen[name] = len(out)
        out.append([name, int(qty)])
    for rune, qty in SWAP_RUNES.items():
        if rune in seen:
            out[seen[rune]][1] += qty
        else:
            seen[rune] = len(out)
            out.append([rune, qty])
    return '&&'.join(p if isinstance(p, str) else '%s=%d' % (p[0], p[1]) for p in out)


def merged_skills(skills):
    """96 Magic unless the spell asks for more; other skills kept."""
    out = []
    magic = SWAP_LEVEL
    for part in [p.strip() for p in skills.split(';') if p.strip()] if skills else []:
        level, name = part.split(' ', 1)
        if name == 'Magic':
            magic = max(magic, int(level))
        else:
            out.append(part)
    return ';'.join(['%d Magic' % magic] + out)


def merged_quests(quests):
    names = [q.strip() for q in quests.split(';') if q.strip()] if quests else []
    if SWAP_QUEST not in names:
        names.append(SWAP_QUEST)
    return ';'.join(names)


def swapped_varbits(varbits):
    conditions = [c for c in varbits.split(';') if c]
    return ';'.join(['4070=2'] + [c for c in conditions if not c.startswith('4070=')])


def main():
    with io.open(PATH, encoding='utf-8', newline='') as f:
        text = f.read()
    nl = '\r\n' if '\r\n' in text else '\n'
    lines = text.split(nl)
    if BEGIN in lines:
        start, end = lines.index(BEGIN), lines.index(END)
        del lines[start:end + 1]
        while lines and lines[-1] == '':
            lines.pop()
    header = lines[0]
    assert header.startswith('# Destination\t'), header
    columns = header[2:].split('\t')
    if 'Note' not in columns:
        columns.append('Note')
        lines[0] = '# ' + '\t'.join(columns)
    col = {name: i for i, name in enumerate(columns)}
    generated = []
    for line in lines[1:]:
        if not line.strip() or line.startswith('#'):
            continue
        cells = line.split('\t')
        cells += [''] * (len(columns) - len(cells))
        varbits = cells[col['Varbits']]
        book = re.match(r'4070=([0-9])', varbits)
        if not book or book.group(1) == '2' or 'Home Teleport' in cells[col['Display info']]:
            continue
        row = list(cells)
        row[col['Items']] = merged_items(cells[col['Items']])
        row[col['Skills']] = merged_skills(cells[col['Skills']])
        row[col['Quests']] = merged_quests(cells[col['Quests']])
        row[col['Duration']] = str(int(cells[col['Duration']]) + SWAP_TICKS)
        row[col['Varbits']] = swapped_varbits(varbits)
        row[col['Note']] = NOTE
        generated.append('\t'.join(row).rstrip('\t'))
    out = lines + ['', BEGIN] + generated + [END, '']
    with io.open(PATH, 'w', encoding='utf-8', newline='') as f:
        f.write(nl.join(out))
    print('%d Spellbook Swap variants written' % len(generated))
    return 0


if __name__ == '__main__':
    sys.exit(main())
